# Site settings
author: Morgaine Lawless
title: KawaiiKoding
header-img: img/home-bg.png
email: morgainelawless@gmail.com
copyright_name: Morgaine Lawless
description: > # this means to ignore newlines until "baseurl:"
  A journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MorgaineLawless

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
